name: Build and Deploy with Trunk

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          target: wasm32-unknown-unknown
          toolchain: nightly
          override: true

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@v1.10.14
          
      - name: Install Trunk
        run: |
          cargo binstall -y --locked trunk
          trunk --version

      - name: Build with Trunk
        run: trunk build --release --public-url /zentore-homepage

      - name: Upload dist as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/
        
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write   
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 
